### ISSUE TITLE
Tradeable item rewards

### ISSUE THREAD

**Issue by dolphinspired** [runeberry/PlayerMadeQuests#120]
Allow quest makers to specify real item rewards for the completion of a quest, with the stipulation that they must trade a specified player to get the reward. Need to add a section onto the quest for something like

```yaml
rewards:
  player: Playername
  item: ItemID
  quantity: 5 # only needed if >1
  # or for multiple rewards
  items:
    - item: ItemID
      quantity: 5
```
Will also need to add a rewards section to the quest completion screen.
